### DISCUSSION TITLE
米家智能直流变频落地扇1X  风扇 功能建议

### DISCUSSION THREAD

**Discussion by id77** [XiaoMi/ha_xiaomi_home#1092] [Ideas]
希望 1X升级版 沿用 1X 的无级调节
"percentage": 1,
"percentage_step": 1.0,

25跨度太大，体验很差，无舒适感

```js
"fan.dmaker_cn_897985270_p5c_s_2_fan": {
    "s": "on",
    "a": {
      "preset_modes": ["直吹风", "自然风"],
      "oscillating": true,
      "percentage": 25,
      "percentage_step": 25.0,
      "preset_mode": "自然风",
      "friendly_name": "米家智能直流变频落地扇1X  风扇",
      "supported_features": 59
    },
    "c": "01JTW9V1GH147VMA75FXMJTZZ9",
    "lc": 1746854053.3938317
  },
  "fan.dmaker_cn_411521641_p5_s_2_fan": {
    "s": "off",
    "a": {
      "preset_modes": ["自然风", "直吹风 "],
      "oscillating": false,
      "percentage": 1,
      "percentage_step": 1.0,
      "preset_mode": "直吹风 ",
      "friendly_name": "米家直流变频落地扇1X  风扇 ",
      "supported_features": 59
    },
    "c": "01JTW9V1GJCH015N836EWQRB6G",
    "lc": 1746854053.3943238
  },
  ```

**Comment by sk7628** [comment]
建议所有风扇类的fan实体都能实现无级调节，单独的那个无极的number属性无法通过bridge接入homekit的

**Reply by id77** [reply]
> 建议所有风扇类的fan实体都能实现无级调节，单独的那个无极的number属性无法通过bridge接入homekit的

哎，1X升级版自然风只有4档25%，50%，75%，100%。直吹风没分开，所以直吹风不能1%-100%调节。

我另外搞了个实体，可以控制这个number，不过手动调整档位太快松开手指可能会回弹档位。语音控制到没有问题。
将就用着先，看官方未来会不会支持。

```yaml
fan:
  - platform: template
    fans:
      bedroom_fan_custom:
        friendly_name: 风扇直吹
        value_template: "{{ is_state('fan.dmaker_cn_897985270_p5c_s_2_fan', 'on') }}"
        percentage_template: "{{ states('number.dmaker_cn_897985270_p5c_speed_level_p_8_1') | int }}"

        turn_on:
          - service: fan.turn_on
            target:
              entity_id: fan.dmaker_cn_897985270_p5c_s_2_fan
          - service: fan.set_preset_mode
            data:
              entity_id: fan.dmaker_cn_897985270_p5c_s_2_fan
              preset_mode: '直吹风'

        turn_off:
          - service: fan.turn_off
            target:
              entity_id: fan.dmaker_cn_897985270_p5c_s_2_fan

        set_percentage:
          - service: number.set_value
            data:
              entity_id: number.dmaker_cn_897985270_p5c_speed_level_p_8_1
              value: '{{ percentage }}'
```
