### DISCUSSION TITLE
Support set_ps for yeelink lamp nightlight mode 请支持床头灯夜灯模式

### DISCUSSION THREAD

**Discussion by manymuch** [XiaoMi/ha_xiaomi_home#675] [Ideas]
Please either
1. add ``set_ps`` method like [xiaomi_miot](https://github.com/al-one/hass-xiaomi-miot)
or 
2. Support ``nightlight`` mode for ``yeelink.light.bslamp2``

For example, here is the action command to trigger nightlight mode in xiaomi_miot

```
action: xiaomi_miot.send_command
data:
  entity_id: light.yeelink_bslamp2_b51b_light
  method: set_ps
  params:
    - nightlight
    - 'on'  
```
