### DISCUSSION TITLE
小爱音箱Pro 无法执行”打开卧室空调“ 文本指令

### DISCUSSION THREAD

**Discussion by ShineQi** [XiaoMi/ha_xiaomi_home#723] [Q&A]
配置信息如下，小爱一直提示没有发现可以操作的空调，要在米家APP里绑定空调，使用action 调试模式，手动输入指令也是如此。
![image](https://github.com/user-attachments/assets/1bf61f90-9f44-4991-a9d7-5ef14a0fcdf8)

```
alias: 使用小爱音箱打开卧室空调
description: ""
triggers:
  - trigger: state
    entity_id:
      - notify.xiaomi_cn_725804221_lx06_execute_text_directive_a_5_5
    attribute: action params
    to: "[\"打开卧室空调\",true]"
  - trigger: state
    entity_id:
      - text.xiaomi_cn_725804221_lx06_execute_text_directive_a_5_5
    attribute: action params
    to: "[\"打开卧室空调\",false]"
conditions: []
actions:
  - device_id: dca3e21fd847a43c63b68e9dd2765254
    domain: text
    entity_id: fbcc8880bf56df63a11b1fce57bb360b
    type: set_value
    value: 正在打开卧室空调
  - type: turn_on
    device_id: c142799c712ff9a65ce9afcb4191a656
    entity_id: 5d5e68de20dfdbc8acad64db7587f01c
    domain: switch
mode: single
```
