### ISSUE TITLE
小米人脸识别智能门锁 X缺少状态

### ISSUE THREAD

**Issue by windowlife** [XiaoMi/ha_xiaomi_home#1050]
### Describe the Bug / 描述问题

缺少状态，但是在米家中枢中是有状态的

### How to Reproduce / 复现步骤

![Image](https://github.com/user-attachments/assets/ab31d043-baf9-4cbc-958d-d88bce4dd044)

![Image](https://github.com/user-attachments/assets/a4ce0a12-d8df-4325-9be2-872bbad9788c)

![Image](https://github.com/user-attachments/assets/39b2c9f2-d370-4693-8780-07d5670bf4cc)

### Expected Behavior / 预期结果

希望能显示更详细的内容

### Reproduce Time / 问题复现的时间点

2025-04-29

### Log Timezone / 日志时区

Asia

### Home Assistant Core Version / Home Assistant Core 版本

2025.4.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

15.1

### Xiaomi Home Integration Version / 米家集成版本

v0.3.1

**Comment by windowlife** [comment]
2025-04-29 12:36:39.624 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_device] event occurred, {'did': '1055970265', 'type': 'event', 'siid': 2, 'eiid': 1, 'arguments': [{'piid': 1, 'value': 3}, {'piid': 2, 'value': 2147876869}, {'piid': 4, 'value': 1745901399}]}
2025-04-29 12:36:39.624 DEBUG (MainThread) [custom_components.xiaomi_home.event] 开锁, attributes: {'操作方式': 3, '操作ID': 2147876869, '当前时间': 1745901399}
2025-04-29 12:36:41.690 DEBUG (739f9b5b646504b5) [custom_components.xiaomi_home.miot.miot_client] 黄先生的家, on broadcast, 10254374731762439923/appMsg/notify/iot/1055970265/event/door_open, 1571022881, local, None, {"did":"1055970265","type":"event","name":"door_open","value":["00"]}
2025-04-29 12:36:41.692 INFO (MainThread) [custom_components.xiaomi_home.miot.miot_client] 黄先生的家, unknown event msg, {"did":"1055970265","type":"event","name":"door_open","value":["00"]}
2025-04-29 12:36:41.694 DEBUG (739f9b5b646504b5) [custom_components.xiaomi_home.miot.miot_client] 黄先生的家, on broadcast, 10254374731762439923/appMsg/notify/iot/1055970265/event/5.1, 1571022882, local, None, {"did":"1055970265","type":"event","siid":5,"eiid":1,"arguments":[{"piid":2,"value":0},{"piid":3,"value":1745901400}]}
2025-04-29 12:36:41.696 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_client] 黄先生的家, local, on event_occurred, {"did":"1055970265","type":"event","siid":5,"eiid":1,"arguments":[{"piid":2,"value":0},{"piid":3,"value":1745901400}]}
2025-04-29 12:36:41.696 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_device] event occurred, {'did': '1055970265', 'type': 'event', 'siid': 5, 'eiid': 1, 'arguments': [{'piid': 2, 'value': 0}, {'piid': 3, 'value': 1745901400}]}
2025-04-29 12:36:41.697 DEBUG (MainThread) [custom_components.xiaomi_home.event] 发生异常, attributes: {'异常情况': 0, '当前时间': 1745901400}

**Comment by angus9487** [comment]
loock.lock.t1门锁
同样希望加入更详细的开关门消息
包括内部外部开锁，用户id方式等

**Comment by SusanPhevos** [comment]
> 1055970265

开锁和发生异常事件的参数定义详见设备 [MIoT-Spec-V2](https://home.miot-spec.com/spec/lumi.lock.bmcn05)
含有 attributes 信息的日志可查看实际产生的事件参数：
2025-04-29 12:36:39.624 DEBUG (MainThread) [custom_components.xiaomi_home.event] 开锁, attributes: {'操作方式': 3, '操作ID': 2147876869, '当前时间': 1745901399}
2025-04-29 12:36:41.697 DEBUG (MainThread) [custom_components.xiaomi_home.event] 发生异常, attributes: {'异常情况': 0, '当前时间': 1745901400}

以开锁事件作为触发，同时设定触发事件参数的自动化可以这样写：
```
triggers:
  - trigger: state
    entity_id:
      - event.lumi_cn_2654_bmcn05_lock_opened_e_2_1
conditions:
  - condition: state
    entity_id: event.lumi_cn_2654_bmcn05_lock_opened_e_2_1
    attribute: 操作方式
    state: 3
actions:
  - action: climate.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: climate.2354_climate
mode: single
```
