### ISSUE TITLE
小爱音箱红外遥控添加的空调目前还没有温控器显示

### ISSUE THREAD

**Issue by Daombledore** [XiaoMi/ha_xiaomi_home#1053]
### Describe the Bug / 描述问题

![Image](https://github.com/user-attachments/assets/3932bd56-706f-4f7d-806c-d334b319d066)
![Image](https://github.com/user-attachments/assets/eaeb3506-c797-4e1d-9ac9-c9e4b111d0ee)

### How to Reproduce / 复现步骤

设备是小爱音箱Play增强版，在隔壁xiaomi miot auto里正常，但是最近登不上去

### Expected Behavior / 预期结果

能更新一下吗

### Reproduce Time / 问题复现的时间点

2025-4-29

### Log Timezone / 日志时区

上海

### Home Assistant Core Version / Home Assistant Core 版本

2025.4.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

Frontend 20250411.0

### Xiaomi Home Integration Version / 米家集成版本

v0.3.1

**Comment by HelloZhuz** [comment]
@Daombledore 空调遥控(miir.aircondition.ir02)这个产品的官方spec只具备写入权限，不具备读取权限。详情可见：http://poc.miot-spec.srv/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-conditioner:0000A004:miir-ir02:1

**Comment by icandura** [comment]
能通过手动配置 configuration.yaml 里面增加 climate 的方式来把它配置成一个空调设备不？
比如我有一个单独的红外遥控器接入了HASS之后是通过 smartIR 库来控制，就是这样写
```
climate:
  - platform: smartir
    name: LivingRoomAC
    unique_id: livingroom_ac
    device_code: 1380
    controller_data: remote.zhi_neng_yao_kong
    temperature_sensor: sensor.zhi_neng_yao_kong_temperature
```
我现在是另外一个房间是用的小米音箱红外遥控板，空调红外遥控、小米温湿度计等已经在小米音箱APP和米家APP配置好了，再通过 xiaomi home 插件来导入HASS的，有什么类似的配置文件写法可以组装成一个设备不？
