### ISSUE TITLE
[Bug]: 空调伴侣需要有个属性能自定义室内温度

### ISSUE THREAD

**Issue by ljk0512** [XiaoMi/ha_xiaomi_home#137]
### Describe the bug / 描述问题

空调伴侣需要有个属性能自定义室内温度，原先用Xiaomi Miot Auto插件是有一个专门属性bind_sensor来自定义的，希望我们插件能出一个属性来定义室内温度

### To Reproduce / 复现步骤

空调伴侣需要有个属性能自定义室内温度，原先用Xiaomi Miot Auto插件是有一个专门属性bind_sensor来自定义的，希望我们插件能出一个属性来定义室内温度

### Expected behavior / 预期结果

空调伴侣需要有个属性能定义室内温度

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.1

**Comment by topsworld** [comment]
您好，后续支持该功能

**Comment by 521tonysteven** [comment]
需要这个功能，希望可以支持将其他可用温度传感器绑定到空调伴侣上

**Comment by shigella520** [comment]
关注

**Comment by SusanPhevos** [comment]
xiaomi_home 根据设备 MIoT-Spec-V2 生成的 HA 实体，实体数据的更新与设备 DID 关联性较强，目前没有有效、可行的方法，能使一个实体的数据来自不同的设备。

以下方法可以将一个空调伴侣和一个温湿度计合并成一个恒温器，能够部分实现 Climate 实体绑定 Sensor 实体的效果。
在 configuration.yaml 中添加
```
climate:
  - platform: generic_thermostat
    name: thermostat_living_room
    heater: switch.ir_ac_heat_sw     
    target_sensor: sensor.miaomiaoc_cn_blt_3_19mem8qdceg00_t2_temperature_p_2_1 # The temperatuer sensor's entity_id
    min_temp: 16
    max_temp: 30
    ac_mode: false     # false, heat; true, cool
    cold_tolerance: 0.5
    hot_tolerance: 0.5
      
script:
  ir_ac_heat:
    alias: "Set acpartner hvac heat"
    sequence:
      - service: climate.set_hvac_mode  # Set the acpartner hvac mode as heat mode
        target:
          entity_id: climate.lumi_cn_4086_mcn04 # The acpartner climate entity's entity_id
        data:
          hvac_mode: heat 
      - service: climate.set_temperature  # Set the acpartner target temperature
        target:
          entity_id: climate.lumi_cn_4086_mcn04
        data:
          temperature: "{{ temperature }}"    

switch:
  - platform: template
    switches:
      ir_ac_heat_sw:
        turn_on:
          - service: script.ir_ac_heat   
            data:
              temperature: "{{ state_attr('climate.thermostat_living_room','temperature')|float(25) }}"            
        turn_off:
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.lumi_cn_4086_mcn04
            data:
              hvac_mode: "off"           
        value_template: "{{ is_state('climate.lumi_cn_4086_mcn04', 'heat') }}"   # acpartner hvac mode determines the switch on/off state
```
[Screencast from 2025年11月13日 11时45分39秒.webm](https://github.com/user-attachments/assets/6fd4e35e-9ff2-4498-aa99-4e717d40a767)

恒温器由关闭变为打开，空调伴侣开启制热模式，并将目标温度设定为与恒温器相同的目标温度26°C，温控器状态变为 Heating。
恒温器将目标温度下调至22.1°C，由于当前温湿度计的温度为23.5°C，温控器状态变为 Idle，空调伴侣关闭空调，停止制热。

这种方法的局限性：
1. 恒温器要么只有制热模式，要么只有制冷模式，无法添加空调伴侣全部的 HVAC 模式。
2. 恒温器只有当目标温度高于当前温度时，才会进入 Heating 状态，从而开启空调伴侣的制热模式。恒温器进入 Idle 状态，会关闭空调伴侣。
3. 空调伴侣状态改变，不会同步给恒温器。
