### ISSUE TITLE
空调插座不支持绑定温度传感器

### ISSUE THREAD

**Issue by mmzhi** [XiaoMi/ha_xiaomi_home#314]
### Describe the Bug / 描述问题

小米空调插座只有目标温度，并没有环境温度

### How to Reproduce / 复现步骤

小米空调插座只有目标温度，并没有环境温度，所以在某些场景，比如homekit中，显示就会有问题，xiaomi-miot控件提供了bind_sensor参数，可以绑定温湿度计，希望插件也能提供类似功能
可参考：https://github.com/al-one/hass-xiaomi-miot/issues/686#issuecomment-1173297983

### Expected Behavior / 预期结果

显示环境温度

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

没使用

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by dydingjiawei** [comment]
mark

**Comment by iguanxi** [comment]
同求空调伴侣增加绑定温度计

**Comment by NeoMan-Hx** [comment]
同求，非常需要这个

**Comment by shigella520** [comment]
关注

**Comment by shihkefa** [comment]
有把空調伴侶轉到Homekit的話很需要這功能!

**Comment by teojs** [comment]
有解决方案了吗

**Comment by jaspercgz** [comment]
请问这个需求还会做吗

**Comment by sashiburi69** [comment]
有进度了吗

**Comment by HackerOO1** [comment]
查不到相关信息，有点想换成miot了，官方好像去年年底说会加的，然后一直没加

**Comment by jerrita** [comment]
any updates here?

**Comment by j1kwen** [comment]
在官方实现绑定传感器功能之前，可以自己先用python_script+自动化临时过渡一下

先在`configuration.yaml`配置文件开启`python_script`
```yaml
python_script:
 ```

在`config`目录下新建一个`python_scripts`目录，再新建一个`.py`文件，文件名随意，假设`update_entity_attr.py`，内容如下
```python
entity_id = data.get("entity_id")
attr_name = data.get("attribute")
attr_value = data.get("value")

if entity_id and attr_name:
    state = hass.states.get(entity_id)
    if state:
        attributes = {} if state.attributes is None else state.attributes.copy()
        attributes[attr_name] = attr_value
        hass.states.set(entity_id, state.state, attributes)

        output["msg"] = f"The attribute {attr_name} of {entity_id} is successfully updated to {attr_value}"
```

重启ha，重启完在`开发者选项-动作`里应该可以搜到`python_script.update_entity_attr`了，名字与前面新建的`.py`文件同名

新建一个自动化，配置参考
```yaml
mode: restart
triggers:
  - entity_id: sensor.temperature_xxxxxx
    trigger: state
  - entity_id:
      - climate.climate_xxxxxxxxx
    attribute: current_temperature
    to: null
    trigger: state
  - event: start
    trigger: homeassistant
actions:
  - variables:
      temperature_sensor: sensor.temperature_xxxxxx
      current_temperature: "{{ states(temperature_sensor) }}"
  - repeat:
      for_each:
        - climate.climate_xxxxxxxxx
      sequence:
        - data:
            entity_id: "{{ repeat.item }}"
            attribute: current_temperature
            value: >-
              {{ current_temperature if current_temperature is number else null }}
          action: python_script.update_entity_attr
alias: 空调绑定温度传感器
description: ""
```

如果空调太多觉得嫌挨个儿写自动化太麻烦，可以用蓝图实现，蓝图配置参考
```yaml
blueprint:
  name: 空调绑定温度传感器
  description: "使climate实体同步当前环境温度。"
  domain: automation
  input:
    target_climates:
      name: 空调
      description: "需要同步温度的空调实体"
      selector:
        entity:
          filter:
            - domain: climate
          multiple: true
    temperature_sensor:
      name: 温度传感器
      description: "获取当前温度的传感器实体"
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: temperature
          multiple: false

mode: restart

trigger:
  - platform: state
    entity_id: !input temperature_sensor
  - platform: state
    entity_id: !input target_climates
    attribute: current_temperature
    to: null
  - platform: homeassistant
    event: start

action:
  - variables:
      temperature_sensor: !input temperature_sensor
      current_temperature: "{{ states(temperature_sensor) }}"
  - repeat:
      for_each: !input target_climates
      sequence:
        - service: python_script.update_entity_attr
          data:
            entity_id: "{{ repeat.item }}"
            attribute: current_temperature
            value: "{{ current_temperature if current_temperature is number else null }}"
```

蓝图导入方式参考官方文档 [Creating an automation blueprint](https://www.home-assistant.io/docs/blueprint/tutorial/)

导入蓝图后，在开发者工具里重新加载一下`自动化（automation）`的配置，不需要重启，新建自动化时选择对应的蓝图，只需要填入空调实体和温度传感器实体就可以了

但这种方式有个弊端，因为是手动新增了一个集成不支持的属性，所以当空调实体的任何状态发生变化时（比如开关机、调整当前温度等），会导致整个状态机被覆盖，`current_temperature`就没了，值变为`null`

而变`null`正是触发自动化的条件之一，还会被改回来，也就是说`current_temperature`会有一个瞬时的由`xx℃`变为`null`再变回`xx℃`的过程，不过这个过程很短，几乎不会被察觉

但是这样的话`current_temperature`属性就不可以再用作其他自动化的触发条件了，因为会导致其他自动化重复触发
