### ISSUE TITLE
八键情景面板V1（cxw.remote.panv01）无法获取准确的entity状态

### ISSUE THREAD

**Issue by ldwnt** [XiaoMi/ha_xiaomi_home#335]
### Describe the Bug / 描述问题

单击按键一2次，第1次单击后entity的numeric_state变为1并不置空，导致第2次单击时状态未变化，因此不会触发对应的automation

### How to Reproduce / 复现步骤

1. 设定一个automation，当单击entity的numeric_state变为1（其实是设置below=2、above=0）时让小爱音箱播放文本“单击按键一”
2. 单击按键一，音箱广播文本
3. 再次单击按键一，音箱不广播文本

### Expected Behavior / 预期结果

单击按键一后，单击entity的numeric_state变为1，随后置空，这样无论连续单击按键一多少次，音箱都会广播文本

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.2

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

0.1.3

**Comment by SusanPhevos** [comment]
请问numeric_state是什么？能不能发一下截图？设备的[MIoT-Spec-V2](https://home.miot-spec.com/spec/cxw.remote.panv01)未找到相应属性或事件。
另外，该设备应该会生成“单击”事件的实体，触发事件时实体详情页会显示是哪一个按键触发了单击事件。

**Comment by ldwnt** [comment]
> 请问numeric_state是什么？能不能发一下截图？设备的[MIoT-Spec-V2](https://home.miot-spec.com/spec/cxw.remote.panv01)未找到相应属性或事件。 另外，该设备应该会生成“单击”事件的实体，触发事件时实体详情页会显示是哪一个按键触发了单击事件。
numeric_state是automation中的一种触发条件：
![image](https://github.com/user-attachments/assets/3a88b160-d10d-4212-b2e6-9b7ad179a8cf)

单击entity：
![image](https://github.com/user-attachments/assets/3d297220-fbc4-4b94-8215-b11a9801ee1f)

automation见下：
```
alias: 按键二单击
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - event.xxx
    attribute: 情景按键
    above: 1
    below: 3
conditions: []
actions:
  - device_id: yyy
    domain: text
    entity_id: zzz
    type: set_value
    value: 按键二单击
mode: single
```
