### ISSUE TITLE
如何在智能音箱播放文本中使用模板

### ISSUE THREAD

**Issue by zengxianxue** [XiaoMi/ha_xiaomi_home#375]
### Describe the Bug / 描述问题

如何在智能音箱播放文本中使用模板

### How to Reproduce / 复现步骤

1. 执行播放文本：`["{{ 现在是: now() }}"]`, `now()`模板函数没有渲染
2. 执行播放文本：`{{ '"[{}]"'.format(1+1) }}` 报错 
```text
无法执行动作“text/set_value” 。 action exec failed, 智能音箱 播放文本(text.xiaomi_cn_867474828_l05c_play_text_a_5_3), invalid action params format, {{ '"[{}]"'.format(1+1) }}
```

### Expected Behavior / 预期结果

播放模板计算结果

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

2024.12.5

### Xiaomi Home Integration Version / 米家集成版本

v0.1.2

**Comment by zengxianxue** [comment]
使用通知实现了

```yaml
action: notify.send_message
metadata: {}
data:
  message: '{{["现在是：{}".format(now())] | to_json}}'
target:
  entity_id: notify.xiaomi_cn_867474828_l05c_play_text_a_5_3
```
