### ISSUE TITLE
建议完善并显示空开和插座等设备的用电量实体等各种状态

### ISSUE THREAD

**Issue by shangtian53** [XiaoMi/ha_xiaomi_home#454]
### Describe the Bug / 描述问题

建议完善并显示空开和插座等设备的用电量实体等各种状态

### How to Reproduce / 复现步骤

建议完善并显示空开和插座等设备的用电量实体等各种状态

### Expected Behavior / 预期结果

建议完善并显示空开和插座等设备的用电量实体等各种状态

### Home Assistant Core Version / Home Assistant Core 版本

2024.11.10

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

### Additional Context / 其他说明

![微信截图_20241225161636](https://github.com/user-attachments/assets/401aeb1d-f41e-4869-a7cb-b053a41c0ca9)
![微信截图_20241225161649](https://github.com/user-attachments/assets/38fd9981-e54a-4c1a-aa10-626363f42ebb)

**Comment by 17754018065** [comment]
Xiaomi Miot Auto里面有用电量等实体，xiaomi home里面没有。

**Comment by mx82705** [comment]
单位也有问题，不能选择

**Comment by Wizard-one** [comment]
电量相关entity没有设置 device_class, state_class 导致无法在 energy中找到电量统计 entities [参见](https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities)

![Image](https://github.com/user-attachments/assets/3ce7aab3-5b93-4039-aef8-3c25963c21e3)

当前设置
```yaml
unit_of_measurement: W
icon: mdi:flash-triangle
friendly_name: 功率
```

xiaomi_miot 设置
```yaml
restored: true
state_class: measurement
device_class: power
friendly_name: 弱电箱插座 power
supported_features: 0
unit_of_measurement: W
```
