### ISSUE TITLE
设备从离线状态恢复后，插件不会自动更新设备的状态，还是在离线状态

### ISSUE THREAD

**Issue by x838902** [XiaoMi/ha_xiaomi_home#462]
### Describe the Bug / 描述问题

1.设备状态离线/在线状态变更后，ha中没有更新

### How to Reproduce / 复现步骤

1.设备离线后查看ha中的设备状态-状态不更新
2.设备重新在线后查看ha中的设备状态-状态不更新
只有重新加载集成，才能显示正确的状态

### Expected Behavior / 预期结果

ha中设备状态同时更新

### Reproduce Time / 问题复现的时间点

2024-12-26

### Log Timezone / 日志时区

上海

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

0.1.4b1

**Comment by yhc1994** [comment]
这个好多人反馈过了，估计后几个版本会更新吧

**Comment by big-mouth-cn** [comment]
有点久了，是还没确认这个问题吗？

**Comment by feidian8352** [comment]
小米电视关机下线后， 再开机中枢无法更新状态，必需重载， 或配置才行，晕了一批

**Comment by zengxianxue** [comment]
同样的问题，目前做了一个定时`reload`的自动化
```yaml
alias: reload_config_entry
description: ""
triggers:
  - trigger: time_pattern
    minutes: /1
conditions: []
actions:
  - action: homeassistant.reload_config_entry
    target:
      area_id: 
        - xxx
        - yyy
    data: {}
mode: single
```
