### ISSUE TITLE
路由器重启之后中枢网关会重复产生上一次虚拟事件

### ISSUE THREAD

**Issue by xjpz** [XiaoMi/ha_xiaomi_home#482]
### Describe the Bug / 描述问题

在路由器重启之前，通过米家APP手动控制产生一条虚拟事件，然后重启路由器当网络再次连接时 会自动产生断网之前的虚拟事件。

### How to Reproduce / 复现步骤

1. 米家APP新建手动控制，执行操作是 中枢网关产生虚拟事件
2. 通过小爱执行步骤1中的手动控制
3. 重启路由器
4. 路由器重启完成，HA中查看到重启之后又一次产生了步骤1中的虚拟事件

### Expected Behavior / 预期结果

重启网络后不要自动产生虚拟事件

### Reproduce Time / 问题复现的时间点

2024-12-28

### Log Timezone / 日志时区

Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

2024.12.4

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

### Additional Context / 其他说明

此问题稳定复。如果使用虚拟事件来控制接入HA的其他设备后，当网络发生变化会执行不可预知的操作。

**Comment by Jurants** [comment]
可能的原因：

在路由器重启和网络恢复期间，米家APP的事件同步机制可能没有正确处理网络中断，导致系统误认为之前的事件尚未被完全处理，因此重新触发。
可能是网络状态恢复后，米家APP或路由器的缓存中仍存有待处理的事件数据，导致事件被再次触发。
建议的解决方法：
<a href="https://unblockedgames-76.io">Unblocked Games 76</a>
检查米家APP和路由器之间的事件同步机制，确保网络恢复时能够准确判断事件的状态。
考虑增加去重逻辑，避免网络断开和恢复过程中事件的重复触发。
查看路由器或米家APP的日志，查看是否有异常记录，可能帮助排查问题根源。

**Comment by temporariness** [comment]
我的笨蛋方案
写个自动化，事件发生10s后，产生一个没用的虚拟事件
```yaml
alias: 事件置空
description: ""
triggers:
  - trigger: state
    entity_id:
      - event.xiaomi_cn_000_hub1_virtual_event_e_4_1
    for:
      hours: 0
      minutes: 0
      seconds: 10
conditions: []
actions:
  - if:
      - condition: state
        entity_id: event.xiaomi_cn_000_hub1_virtual_event_e_4_1
        attribute: 事件名称
        state: nop
    then: []
    else:
      - action: notify.send_message
        metadata: {}
        data:
          message: "[\"nop\"]"
        target:
          entity_id: notify.xiaomi_cn_000_hub1_emit_virtual_event_a_4_1
mode: single
```
