### ISSUE TITLE
米家八鍵旋鈕開關沒有各別按鍵及旋鈕的觸發事件

### ISSUE THREAD

**Issue by nonamelee1003** [XiaoMi/ha_xiaomi_home#532]
### Describe the Bug / 描述问题

米家八鍵旋鈕開關沒有各別按鍵及旋鈕的觸發事件

### How to Reproduce / 复现步骤

![IMG_0256](https://github.com/user-attachments/assets/f0ce3b24-afa8-4991-ac18-0f6598408c7c)
米家八鍵旋鈕開關沒有八顆按鍵及旋鈕左旋右旋跟旋鈕按壓的觸發事件，無法執行自動化場景

### Expected Behavior / 预期结果

可以各別控制八顆實體按鍵（單按/雙按/長按）及八顆按鍵模式底下的旋鈕的左旋、右旋跟旋鈕按壓的觸發，共計48個自動化觸發事件

### Reproduce Time / 问题复现的时间点

2025-01-01 12:00

### Home Assistant Logs / 系统日志

![IMG_0258](https://github.com/user-attachments/assets/b627e5cf-da6d-4054-9295-59c30e919e36)

### Log Timezone / 日志时区

Asia

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.14

### Additional Context / 其他说明

無

**Comment by JimmyKmi** [comment]
参考https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/6k65ash5bge5ocn57y65asx-S3aYBqlRvw

**Comment by nonamelee1003** [comment]
在Xiaomi gateway3的程式中是有八鍵控制單擊 雙擊 長按 及八鍵底下的左旋 右旋控制
但在Xiaomi home 底下不管點擊一到八的哪個按鍵,都只有顯示一個按鍵的事件
![Image](https://github.com/user-attachments/assets/8bf69ad0-0234-4c5a-940f-53f0265e07e5)
![Image](https://github.com/user-attachments/assets/f431222d-ce14-44bf-b570-04cb42c98971)

**Comment by nonamelee1003** [comment]
![Image](https://github.com/user-attachments/assets/fd9c03d7-4e1c-4570-b176-fd64a5f27098)
![Image](https://github.com/user-attachments/assets/5520f416-975e-488b-9dfb-6db738f6f740)
![Image](https://github.com/user-attachments/assets/871b71f9-872f-45fa-a68c-c15e11173581)

**Comment by SusanPhevos** [comment]
设备 [MIoT-Spec-V2](http://poc.miot-spec.srv/miot-spec-v2/instance?type=urn:miot-spec-v2:device:remote-control:0000A021:cxw-ble006:1) 的单击、双击、旋转、长按事件有参数，参数代表按键类型。
v0.2.2 之后，将日志设置为 debug 级别可查看事件所携带的事件参数（日志搜索关键字attributes）。

**Comment by nonamelee1003** [comment]
[home-assistant_xiaomi_home_2025-03-27T13-27-50.789Z.log](https://github.com/user-attachments/files/19487299/home-assistant_xiaomi_home_2025-03-27T13-27-50.789Z.log)

**Comment by nonamelee1003** [comment]
照log 檔設定按鈕1，Scenario Buttons為1一樣不能執行自動化
![Image](https://github.com/user-attachments/assets/be582458-dc92-4437-b8ad-0712487bdd68)

**Comment by SusanPhevos** [comment]
Create new automation > ADD TRIGGER > Entity > State > When Entity, 选择 entity_id 例如 event.cxw_cn_blt_3_1l63uh2vocg01_ble006_click_e_5_1012 > Attribute (optional), 填写 Scenario Buttons > To (optional), 填写 1 > 点击右上角三个点的图标 > Edit in yaml > 去掉数值 1 的双引号
最终yaml文件就像这样：

![Image](https://github.com/user-attachments/assets/c59f3c47-56af-4b02-b116-a333661a5788)

**Comment by nonamelee1003** [comment]
我依照您的設定新增自動化
但都只能在第一次觸發成功開啟電燈
第二次後就無反應了

![Image](https://github.com/user-attachments/assets/578482c0-43a8-4c20-8690-af0794df3019)

**Comment by Rebuilding127** [comment]
> 我依照您的設定新增自動化 但都只能在第一次觸發成功開啟電燈 第二次後就無反應了
> 
> ![Image](https://github.com/user-attachments/assets/578482c0-43a8-4c20-8690-af0794df3019)

我遇到过类似的，解决方案是把触发的具体条件写到`conditions`中而非`triggers`，参考：

```
triggers:
  - trigger: state
    entity_id:
      - event.xiaomi_cn_1072912250_hub1_virtual_event_e_4_1
conditions:
  - condition: state
    entity_id: event.xiaomi_cn_1072912250_hub1_virtual_event_e_4_1
    attribute: 事件名称
    state: 打开空调
actions:
  - action: climate.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: climate.208907221107829_climate
mode: single
```

当时我拿其它设备做过测试，猜测应该是将条件写在`triggers`时，如果状态未变化过，那不会重复触发，更接近于判断是否从其它状态变化到指定的条件状态。而写在`conditions`中，那只会判断条件是否成立，成立即执行。

例如假设某状态当前值为0，即 `state=0` 
假设条件 `state==1` 触发，那重复给state赋值为1只会在第一次有效，第二次开始就无效了，因为它没有变化过。
但如果状态变化改为 `state=1 -> state=2 -> state=1` ，那两次都会触发。
