### ISSUE TITLE
Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### ISSUE THREAD

**Issue by AbianTang** [XiaoMi/ha_xiaomi_home#574]
### Describe the Bug / 描述问题

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### How to Reproduce / 复现步骤

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  
<img width="568" alt="截屏2025-01-04 21 52 58" src="https://github.com/user-attachments/assets/b9f7dade-5ce0-4491-ab31-68073b03b55a" />
需改成presence如下，不然无法进行自动化
<img width="558" alt="截屏2025-01-04 21 53 49" src="https://github.com/user-attachments/assets/e5e12b0f-dd78-484d-a96c-d9cd8f5a20b5" />

### Expected Behavior / 预期结果

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### Reproduce Time / 问题复现的时间点

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### Home Assistant Logs / 系统日志

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### Log Timezone / 日志时区

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### Home Assistant Core Version / Home Assistant Core 版本

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### Home Assistant Operation System Version / Home Assistant Operation System 版本

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence  

### Xiaomi Home Integration Version / 米家集成版本

Xiaomi Motion Sensor 2S Motion Sensor 建议修改为ha的presence

**Comment by caibinqing** [comment]
`event` 是可以用的，也是HA最新建议的写法，（我也觉得不是很好用，尽管它比较正确）
自动化的触发条件可以像这样写：
```yaml
trigger: state
entity_id:
  - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
not_from: unavailable
not_to: unavailable
```

**Comment by AbianTang** [comment]
> `event` 是可以用的，也是HA最新建议的写法，（我也觉得不是很好用，尽管它比较正确） 自动化的触发条件可以像这样写：
> 
> ```yaml
> trigger: state
> entity_id:
>   - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
> not_from: unavailable
> not_to: unavailable
> ```
应该是这样吧
`platform: state
entity_id:
  - event.xiaomi_cn_blt_3_1jsub7bnc4g03_pir1_motion_detected_e_2_1008
attribute: event_type
from: 检测到移动
to: 检测到移动
`

**Comment by dante210402** [comment]
> ``
> 
> > `event` 是可以用的，也是HA最新建议的写法，（我也觉得不是很好用，尽管它比较正确） 自动化的触发条件可以像这样写：
> > ```yaml
> > trigger: state
> > entity_id:
> >   - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
> > not_from: unavailable
> > not_to: unavailable
> > ```
> 
> ```yaml
> platform: state
> entity_id:
>   - event.xiaomi_cn_xxxxxxxxxxxx
> from: 检测到移动
> to: 检测到移动
> ```
> 
> 应该是这样吧

这个事件的值不是检测到移动，而且一个触发时间，可以自己模板里创建一个二元传感器，虽然我觉着现在这么做不太优雅
```yaml
{% set temp = as_timestamp(states('event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008')) -%}
{%- if as_timestamp(now()) - temp > 60 -%}
OFF
{%- else -%}
ON
{% endif %}
 ```

**Comment by caibinqing** [comment]
> ```yaml
> platform: state
> entity_id:
>   - event.xiaomi_cn_xxxxxxxxxxxx
> from: 检测到移动
> to: 检测到移动
> ```
> 
> 应该是这样吧

不是这样的，状态是触发的时间戳，所以才能监听到变化（这个motion事件只有一种类型，就不需要判断了），完整的自动化可以参考这个：

```yaml
mode: restart
triggers:
  - trigger: state
    entity_id:
      - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
    not_from: unavailable
    not_to: unavailable
conditions: []
actions:
  - alias: 如果灯关着就打开
    if:
      - condition: state
        entity_id: light.*************
        state: "on"
    then:
      - action: light.turn_on
        target:
          entity_id: light.*************
        data: {}
  - alias: 等一会儿
    delay:
      hours: 0
      minutes: 2
      seconds: 0
  - alias: 关灯
    action: light.turn_off
    target:
      entity_id: light.*************
    data: {}
```

**Comment by AbianTang** [comment]
> > ```yaml
> > platform: state
> > entity_id:
> >   - event.xiaomi_cn_xxxxxxxxxxxx
> > from: 检测到移动
> > to: 检测到移动
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该是这样吧
> 
> 不是这样的，状态是触发的时间戳，所以才能监听到变化（这个motion事件只有一种类型，就不需要判断了），完整的自动化可以参考这个：
> 
> ```yaml
> mode: restart
> triggers:
>   - trigger: state
>     entity_id:
>       - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
>     not_from: unavailable
>     not_to: unavailable
> conditions: []
> actions:
>   - alias: 如果灯关着就打开
>     if:
>       - condition: state
>         entity_id: light.*************
>         state: "on"
>     then:
>       - action: light.turn_on
>         target:
>           entity_id: light.*************
>         data: {}
>   - alias: 等一会儿
>     delay:
>       hours: 0
>       minutes: 2
>       seconds: 0
>   - alias: 关灯
>     action: light.turn_off
>     target:
>       entity_id: light.*************
>     data: {}
> ```

```yaml
description: ""
mode: restart
triggers:
  - trigger: state
    entity_id:
      - event.xiaomi_cn_blt_3_xxxxxxxxxxxx_pir1_motion_detected_e_2_1008
    not_from: unavailable
    not_to: unavailable
conditions: []
actions:
  - alias: 如果灯关着就打开
    if:
      - condition: state
        entity_id: light.yeelink_cn_xxxxxxxxxceiling22_s_2
        state: "on"
    then:
      - action: light.turn_on
        target:
          entity_id: light.yeelink_cnxxxxxxxxx_ceiling22_s_2
        data: {}
  - alias: 等一会儿
    delay:
      hours: 0
      minutes: 2
      seconds: 0
  - alias: 关灯
    action: light.turn_off
    target:
      entity_id: light.yeelink_xxxxxxxxxxxxxxxxxxx22_s_2
    data: {}
alias: 新建自动化
```
错误Message malformed: extra keys not allowed @ data['triggers']

**Comment by AbianTang** [comment]
还是感觉presence优雅，2s人体传感器event五颜六色在ha看起来都怪怪的。

**Comment by caibinqing** [comment]
> 错误Message malformed: extra keys not allowed @ data['triggers']

旧版本大概是这样写的：
```yaml
mode: restart
trigger:
  - platform: state
    entity_id:
      - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
    not_from: unavailable
    not_to: unavailable
condition: []
action:
  - alias: 如果灯关着就打开
    if:
      - condition: state
        entity_id: light.*************
        state: "on"
    then:
      - service: light.turn_on
        target:
          entity_id: light.*************
        data: {}
  - alias: 等一会儿
    delay:
      hours: 0
      minutes: 2
      seconds: 0
  - alias: 关灯
    service: light.turn_off
    target:
      entity_id: light.*************
    data: {}
```

**Comment by 13860605362** [comment]
> > 错误Message malformed: extra keys not allowed @ data['triggers']
> 
> 旧版本大概是这样写的：
> 
> mode: restart
> trigger:
>   - platform: state
>     entity_id:
>       - event.xiaomi_cn_blt_3_*************_pir1_motion_detected_e_2_1008
>     not_from: unavailable
>     not_to: unavailable
> condition: []
> action:
>   - alias: 如果灯关着就打开
>     if:
>       - condition: state
>         entity_id: light.*************
>         state: "on"
>     then:
>       - service: light.turn_on
>         target:
>           entity_id: light.*************
>         data: {}
>   - alias: 等一会儿
>     delay:
>       hours: 0
>       minutes: 2
>       seconds: 0
>   - alias: 关灯
>     service: light.turn_off
>     target:
>       entity_id: light.*************
>     data: {}

没有not_from的选项，只能ymal编辑，有点麻烦。我用自定义超时无人移动时间判断有人/无人。每次有人的情况下  无人移动时间就会变成0。但是之前出现过一次没有人移动，但是也变成0的情况。

**Comment by caibinqing** [comment]
> 没有not_from的选项，只能ymal编辑，有点麻烦。我用自定义超时无人移动时间判断有人/无人。每次有人的情况下 无人移动时间就会变成0。但是之前出现过一次没有人移动，但是也变成0的情况。

嗯 没有可视化确实不太方便，但这种比较稳定。而且自动化嘛也不会经常去编辑，同类多的话还可以自己写蓝图。

**Comment by 13860605362** [comment]
> > 没有not_from的选项，只能ymal编辑，有点麻烦。我用自定义超时无人移动时间判断有人/无人。每次有人的情况下 无人移动时间就会变成0。但是之前出现过一次没有人移动，但是也变成0的情况。
> 
> 嗯 没有可视化确实不太方便，但这种比较稳定。而且自动化嘛也不会经常去编辑，同类多的话还可以自己写蓝图。

你人体传感器这类的也是用这种方式判断么？

**Comment by caibinqing** [comment]
> 你人体传感器这类的也是用这种方式判断么？

嗯，上面那段不就是我发的么，我现在 motion 类的都是用的这个结构，只用一个 event 来触发，这样时间什么的也都在HA里控制，米家的那些 无人移动时间 我都禁用了。

**Comment by 13860605362** [comment]
> > 你人体传感器这类的也是用这种方式判断么？
> 
> 嗯，上面那段不就是我发的么，我现在 motion 类的都是用的这个结构，只用一个 event 来触发，这样时间什么的也都在HA里控制，米家的那些 无人移动时间 我都禁用了。

我之前没用过ymal编辑自动化，只是偶尔用模板作为条件。不知道用not_to，用的from任何状态to任何状态。结果更新一下设备列表就会触发一堆自动化。。。

**Comment by caibinqing** [comment]
> 我之前没用过ymal编辑自动化，只是偶尔用模板作为条件。不知道用not_to，用的from任何状态to任何状态。结果更新一下设备列表就会触发一堆自动化。。。

对，我也是最近用这个 event 发现这个坑，才搜到还有 not_from 这种字段

**Comment by AbianTang** [comment]
> > 没有not_from的选项，只能ymal编辑，有点麻烦。我用自定义超时无人移动时间判断有人/无人。每次有人的情况下无人移动时间就会变成0。但是之前出现过一次没有人移动，但是也变成0的情况。
> 
> 嗯没有可视化确实不太方便，但比较稳定。而且自动化嘛也不会经常去编辑，同类多的话还可以自己写这种蓝图。
这样手动事件可以可视化
```yaml
event_type: state_changed
event_data:
  entity_id: event.xiaomi_cn_blt_3_1jx x x x x x x x x x x x x x_motion_detected_e_2_1008
trigger: event
```
