### ISSUE TITLE
[Bug]: 无法登录

### ISSUE THREAD

**Issue by Itoktsnhc** [XiaoMi/ha_xiaomi_home#64]
### Describe the bug / 描述问题

登录跳转后提示获取OAuthToken失败

### To Reproduce / 复现步骤

1. HA使用docker部署:
```
services:
  homeassistant:
    container_name: homeassistant
    ports:
      - "8123:8123"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/ipool/_docker_home/config/homeassisant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
```
2. custom_components/xiaomi_home 复制到对应目录
3. 配置hosts使用homeassistant.local:8123访问ha
4. 添加Xiaomi Home，登录
5. 跳转回HA提示获取OAuthToken失败

### Expected behavior / 预期结果

登录成功

### Home Assistant Logs / 系统日志

![image](https://github.com/user-attachments/assets/f1fc8ee4-1ee7-4e48-9436-c6399b22a3c0)
使用curl 访问相同地址的结果(间隔大概2分钟)
![image](https://github.com/user-attachments/assets/9cab5326-2c1a-4d1c-b9de-fcb8d64e650d)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

--

### Xiaomi Home integration version / 米家集成版本

--
