### ISSUE TITLE
领普开关KS1PRO无四按键单独事件

### ISSUE THREAD

**Issue by Lucas-lyh** [XiaoMi/ha_xiaomi_home#699]
### Describe the Bug / 描述问题

没有每个按键的单独事件，仅有全部按键都会触发的事件。

### How to Reproduce / 复现步骤

配对领普KS1PRO

### Expected Behavior / 预期结果

有四个按键的单独事件

### Reproduce Time / 问题复现的时间点

任意时间

### Log Timezone / 日志时区

Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2025.1.2

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.5b2

### Additional Context / 其他说明

![Image](https://github.com/user-attachments/assets/76786892-70d8-443b-aac4-39d6aba98cbe)

![Image](https://github.com/user-attachments/assets/856090c7-f1d9-4926-9d6a-d8c2b7dbffbc)

**Comment by Lucas-lyh** [comment]
![Image](https://github.com/user-attachments/assets/b8b4b16d-f67c-49e7-9760-f1d0e76c3fd4)

米家中可以正常显示按键几被触发

**Comment by caibinqing** [comment]
在开发者工具里观察它的状态可以看到有个`按键类型`的字段。

自动化可以参考这样写：

```yaml
triggers:
  - trigger: state
    entity_id:
      - event.linp_cn_blt_3_1************_ks1bp_click_e_5_1012
    not_from: unavailable
    not_to: unavailable
conditions:
  - condition: state
    entity_id: event.linp_cn_blt_3_1************_ks1bp_click_e_5_1012
    attribute: 按键类型
    state: 3
```
