### ISSUE TITLE
米家人体传感器2、米家夜灯2蓝牙版无法以人体传感器的形式显示检测到移动状态

### ISSUE THREAD

**Issue by Ungs22** [XiaoMi/ha_xiaomi_home#884]
### Describe the Bug / 描述问题

米家人体传感器2、米家夜灯2蓝牙版无法以人体传感器的形式显示检测到移动状态

### How to Reproduce / 复现步骤

米家人体传感器2、米家夜灯2蓝牙版无法以人体传感器的形式显示检测到移动状态，如下图，在HA中是以事件的形式来表示当前有人正在移动，但一些第三方插件，比如matter-hub，用于将HA中的设备接入到别的平台，就无法识别这种事件类型，无法把它当作传感器进行处理。
![Image](https://github.com/user-attachments/assets/3a83cb2c-3893-44f0-b2d4-5f52bd4aa867)

![Image](https://github.com/user-attachments/assets/c0e51e56-3383-4743-8770-4dae5a054351)

以下为另一插件的人体传感器样式，请问下开发团队能否使用这样的形式表示检测到人体移动，这样方便接入其他第三方程序，谢谢

![Image](https://github.com/user-attachments/assets/eff6b504-3f54-4bf2-86cd-1b8e3fb0d4c0)

### Expected Behavior / 预期结果

使用标准的Motion Sensor表示移动，图片上传在了复现步骤中

### Reproduce Time / 问题复现的时间点

2025-03-14 15:45:00

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2025.3.0

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.2

### Xiaomi Home Integration Version / 米家集成版本

0.2.2

**Comment by SusanPhevos** [comment]
另一插件的人体传感器在设备详情页里的显示效果是怎样的？设备实体属于“传感器”类型吗？

**Comment by Ungs22** [comment]
另一插件是Xiaomi Miot Auto，设备详情页效果是这样的，

![Image](https://github.com/user-attachments/assets/7658df27-f20f-4e55-a8fe-4bdc7022f087) 属于传感器类型，这样的传感器形式才可以被matter-hub这一类第三方插件正确识别。另外请问下水浸传感器在xiaomi home插件中是这样显示的，

![Image](https://github.com/user-attachments/assets/5d1d65c0-1ff7-46f6-8bf3-27ceee28714b) ，会被第三方插件识别为门磁，即不浸水时识别为门磁关闭（但在aqara的定义里，门磁关闭表示浸水），导致其它matter平台识别错误。

**Comment by micturkey** [comment]
> 另一插件的人体传感器在设备详情页里的显示效果是怎样的？设备实体属于“传感器”类型吗？

这里还有xiaomigateway3插件的效果：

![Image](https://github.com/user-attachments/assets/11b47633-7ad2-4980-851a-e367d2e4c778)

![Image](https://github.com/user-attachments/assets/866ec00c-8896-41c9-a90d-c18c2f3ca50d)

![Image](https://github.com/user-attachments/assets/108ff947-6230-40da-bff9-d1c64061d2ae)

可以看到，每一个类型的传感器都对应着正确的设备类型

**Comment by caibinqing** [comment]
目前可以用这种方法把 `motion` 的 `event` 转换成 `binary_sensor`，
完美转换，而且可以自定义超时时间。（其实对于集成自己实现成`binary_sensor`最大的问题大概就是超时时间不好定）
缺点就是必须去yaml里写，不支持UI创建，也不能关联到设备。

```yaml
# configuration.yaml
template:
  - trigger:
      - platform: state
        entity_id: event.xiaomi_cn_blt_3_1**********00_pir1_motion_detected_e_2_1008
        not_from: unavailable
        not_to: unavailable
    binary_sensor:
      - name: "有人移动"
        unique_id: ****************
        device_class: motion
        state: "on"
        auto_off:
          seconds: 15
```

---

另外的 水浸、门窗、人在 可以看下我这个PR #905
