### ISSUE TITLE
更新实体转换规则触发了开灯

### ISSUE THREAD

**Issue by Cigarrr** [XiaoMi/ha_xiaomi_home#917]
### Describe the Bug / 描述问题

更新实体转换规则提交时，触发部分灯具开灯

### How to Reproduce / 复现步骤

1. 灯具处于关闭状态
![Image](https://github.com/user-attachments/assets/b8f4950d-b13e-4216-88ac-68a37602bb28)
2. 在HA集成-XIAOMI_HOME-中枢配置页面，选中“更新实体转换规则”，连续下一步直至提交
3. 部分灯具被打开

### Expected Behavior / 预期结果

所有设备应保持“更新实体转换规则”前的状态

### Reproduce Time / 问题复现的时间点

2025-03-22 11:40:00

### Home Assistant Logs / 系统日志

[home-assistant_2025-03-22T03-46-21.206Z.log.zip](https://github.com/user-attachments/files/19400550/home-assistant_2025-03-22T03-46-21.206Z.log.zip)

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2025.3.0

### Home Assistant Operation System Version / Home Assistant Operation System 版本

容器版本

### Xiaomi Home Integration Version / 米家集成版本

v0.2.3

### Additional Context / 其他说明

任意版本均有此现象

另外，每次更新实体转换规则，都会有需要更新的规则，这是正常吗的？

**Comment by Cigarrr** [comment]
更新设备列表也会触发。

**Comment by caibinqing** [comment]
检查一下是不是 `event` 实体触发的自动化，event 作为触发条件目前需要加上 not_from 和 not_to, 例如
```yaml
trigger: state
entity_id:
  - event.xxxxxxxxxxxxxxxxxxxxxxxxxx
not_from: unavailable
not_to: unavailable
```

**Comment by rumianoesa** [comment]
我试过not_from: unavailable是没用的
因为xiaomi_home的事件实体在初始化时是从一个空事件变成上一个事件
目前我的解决方法是在自动化判断条件里判断电池实体是不是unavailable，不是才执行

**Comment by caibinqing** [comment]
> 我试过not_from: unavailable是没用的 因为xiaomi_home的事件实体在初始化时是从一个空事件变成上一个事件 目前我的解决方法是在自动化判断条件里判断电池实体是不是unavailable，不是才执行

`not_from: unavailable` + `not_to: unavailable` 对于我现有的设备都是够用的，那也许你可以试试加个 unknown ?
```yaml
not_from:
  - unavailable
  - unknown
not_to: unavailable
```
