### ISSUE TITLE
开关类事件重复触发

### ISSUE THREAD

**Issue by willhcz** [XiaoMi/ha_xiaomi_home#925]
### Describe the Bug / 描述问题

无线场景开关(六键版)，因为在mihone里设置的全部为事件，每次重新设置、重启插件后都会自动全部触发一次开关事件，导致开关全部都会自动执行一次。

### How to Reproduce / 复现步骤

1、重启插件、重新设置插件。
2、开关的自动化全部自动执行一次。

### Expected Behavior / 预期结果

重启不会导致自动执行一次。

### Reproduce Time / 问题复现的时间点

2025-03-23-22:00

### Log Timezone / 日志时区

shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2025.3.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

15.0

### Xiaomi Home Integration Version / 米家集成版本

v0.2.3

**Comment by caibinqing** [comment]
event 作为触发条件目前需要加上 not_from 和 not_to, 例如

```yaml
trigger: state
entity_id:
  - event.xxxxxxxxxxxxxxxxxxxxxxxxxx
not_from: unavailable
not_to: unavailable
```
